### ISSUE TITLE
Cloudflare api key

### ISSUE THREAD

**Issue by MostHated** [Mezzle/media-docker#1]
Hey man,  
  I came across your repo when trying to find how to add the cloudflare plugin for caddy and I noticed you accidentally uploaded your cloudflare api key in your docker-compose file. You definitely should make that a variable and put it into an .env file and then .gitignore the .env file so it doesn't get uploaded by accident!

That being said, were you actually able to build your caddy image from the context using the cloudflare plugin? Every time I try, even when using --no-cache, I keep getting this every time for some reason:

    The command '/bin/sh -c VERSION=${version} PLUGINS=${plugins} /bin/sh /usr/bin/builder.sh' returned a non-zero code: 1

Thanks,  
-MH

**Comment by Mezzle** [comment]
Hey, Thanks, This is now changed, don't know how I missed this issue for so long.

Hope you've got caddy to build.  It built fine for me in this manner...
